import type { Metadata } from "next";
import { APP_NAME, MAINTAINER_NAME, MAINTAINER_URL, SOURCE_URL } from "./config";
import { LANGUAGES } from "./preferences";

/**
 * What search engines and link previews see: the site's address, the title
 * and description of each page, which pages are worth indexing, and the
 * structured data for the application. English only: a static export has one
 * <head> per page and cannot vary it by language (the app switches language
 * after hydration, see preferences-store.ts).
 *
 * The sitemap and robots routes (app/sitemap.ts, app/robots.ts) and every
 * page's metadata come from PAGES, so a page cannot be in the sitemap and
 * marked noindex at the same time.
 */

/** The public address, without a trailing slash. */
export const SITE_URL = "https://ideamatrix.io";

/** The one-line tagline, for link previews; the same sentence as the README. */
export const TAGLINE =
  "Score your project ideas, and keep the file yourself. No accounts, no server, nothing leaves your machine.";

/**
 * The home page's description, written the way someone with too many ideas
 * would search: score, rank, decide what to work on next, and keep the file.
 * Under 160 characters so a result shows all of it.
 */
export const DESCRIPTION =
  "Too many project ideas? Score each one, let real evidence set the ranking, and decide what to work on next. No accounts, no server: the file stays yours.";

/** The link-preview image for the GitHub repository, also generated by scripts/icons.mjs, at a stable URL. */
export const PREVIEW_IMAGE = "/social-preview.png";

export interface PageInfo {
  /** The tab title before " · Idea Matrix"; the home page is just the app name. */
  title?: string;
  /** For the pages a search engine should show; the others need none. */
  description?: string;
  /**
   * Whether search engines should index it. Only the pages a stranger can
   * read: the home page (which sends a newcomer to setup), setup itself and
   * the privacy page. The screens that need an open matrix show a loading
   * message to a crawler and someone's own ideas to the person, so they are
   * noindex and out of the sitemap.
   */
  index: boolean;
}

export const PAGES = {
  "/": { description: DESCRIPTION, index: true },
  "/setup/": {
    title: "Score your project ideas",
    description:
      "Get started: how ideas are scored, how Confidence counts the evidence, and where your file lives, on your computer or in Google Drive. Nothing to install.",
    index: true,
  },
  "/privacy/": {
    title: "Privacy and trust",
    description:
      "Where your ideas file lives, what the app sends (nothing), and how to check that for yourself in the browser’s Network tab.",
    index: true,
  },
  "/idea/": { title: "Idea", index: false },
  "/parked/": { title: "Parked", index: false },
  "/settings/": { title: "Settings", index: false },
} as const satisfies Record<string, PageInfo>;

export type PagePath = keyof typeof PAGES;

/** The pages the sitemap lists, in the order above. */
export function indexedPaths(): PagePath[] {
  return (Object.keys(PAGES) as PagePath[]).filter((path) => PAGES[path].index);
}

/** The `metadata` export for a page: its title, and either a description with a canonical URL or a noindex. */
export function pageMetadata(path: PagePath): Metadata {
  const page: PageInfo = PAGES[path];
  const title = page.title ?? { absolute: APP_NAME };
  if (!page.index) return { title, robots: { index: false, follow: false } };
  return { title, description: page.description, alternates: { canonical: path } };
}

/**
 * Schema.org structured data for the application, on every page. App
 * constants only, no user text, and no version: the version changes with
 * every release and would go stale here.
 */
export function structuredData() {
  return {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: APP_NAME,
    url: `${SITE_URL}/`,
    description: DESCRIPTION,
    image: `${SITE_URL}${PREVIEW_IMAGE}`,
    applicationCategory: "BusinessApplication",
    operatingSystem: "Any",
    browserRequirements: "Saving to a file on this computer needs Chrome or Edge; Google Drive works in any browser.",
    isAccessibleForFree: true,
    offers: { "@type": "Offer", price: "0", priceCurrency: "CAD" },
    license: `${SOURCE_URL}/blob/main/LICENSE`,
    inLanguage: [...LANGUAGES],
    featureList: [
      "Score each idea from 1 to 5 for Reach, Impact, Profitability, Vision and Ease",
      "Confidence counts the evidence from real conversations, and nothing ranks high without it",
      "One file you keep, on your computer or in Google Drive; no accounts and no server",
      "Works with AI assistants through the Model Context Protocol",
    ],
    author: { "@type": "Person", name: MAINTAINER_NAME, url: MAINTAINER_URL },
    sameAs: [SOURCE_URL],
  };
}

/**
 * The structured data as the text of a <script type="application/ld+json">.
 * React writes a script's string child as-is, so every "<" becomes the JSON
 * escape \u003c (the same string once parsed) and no value can close the
 * script element early. The values are constants, so this is belt and
 * braces rather than a defence against user text.
 */
export function structuredDataJson(): string {
  return JSON.stringify(structuredData()).replace(/</g, "\\u003c");
}
